config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  post 'users/api_sign_in' => "users#api_sign_in"

  resources :posts, only: [:create, :index]

  resources :comments, only: [:create]

  get "likes/toggle", as: "like_toggle"

  get "users/my_profile"

  patch "users/update" => "users#update", as: "user"
    
  root "posts#index"

  namespace :api do
  	namespace :v1 do
  		get 'posts' => 'posts#index'
    end
  end


  require "resque_web"
  
  mount ResqueWeb::Engine => "/resque_web"





end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	
	belongs_to :parent, polymorphic: true

	has_many :comments, as: :parent
	has_many :likes, as: :parent

	def user_can_like(user)
		return !(self.likes.find_by(user: user))
	end

	def current_like_status_string(user)
		if user_can_like(user)
			return 'Like'
		else
			return 'Unlike'
		end

	end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

	belongs_to :user


	
	belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ActiveRecord::Base


	belongs_to :user
	belongs_to :parent, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	has_many :comments, as: :parent
	has_many :likes, as: :parent

	def user_can_like(user)
		return !(self.likes.find_by(user: user))
	end

	def current_like_status_string(user)
		if user_can_like(user)
			return '<i class="fa fa-thumbs-o-up"></i>'
		else
			return '<i class="fa fa-thumbs-o-down"></i>'
		end

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

         # you can add some styles for different sizes
  has_attached_file :avatar, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  has_many :posts	
  has_many :comments
  has_many :likes

  has_many :friendships
  has_many :friends, through: :friendships


  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'

  has_many :inverse_friends, through: :inverse_friendships, source: :user




  # def age
  # 	return (Time.now - dob).years
  # end
  def self.from_omniauth(access_token)
    byebug
    data = access_token.info
    user = User.where(email: data['email']).first

    
    unless user
        user = User.create(
           email: data['email'],
           password: Devise.friendly_token[0,20],
           confirmed_at: Time.now
        )
    end
    user
  end 

  def set_auth_token
    self.auth_token = SecureRandom.hex
    self.token_is_valid = true
    self.save
  end






end


# @user = User.find(10)
# @user.age

app/controllers/api/v1/posts_controller.rb
module Api
	module V1

		class  PostsController < ApplicationController
			skip_before_action :verify_authenticity_token, only: [:create]
			before_action :authenticate_user_custom, only: [:create]

			def index

				@post = Post.new
				@comment = Comment.new
				# @posts = Post.all
				@page = params[:page].blank? ? 1 : params[:page].to_i
				@count = params[:count].blank? ? 2 : params[:count].to_i

				@max_pages = Post.all.length/@count
				
				@posts = Post.offset((@page - 1) * @count).limit(@count)

				query = params[:term]
				@posts = @posts.where('content like ? ', ('%' + query + '%'))

				return render json: @posts, adapter: :json, root: "posts"

				
			end


		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authenticate_user_custom


  	if user_signed_in?
  		@current_user = current_user
  	else

  		authenticate_with_http_token do |token, options|
        
  			@current_user = User.find_by(auth_token: token)
  		end

  	end

  	if @current_user.blank?
  		return render json: {message: 'Unauthorized', status: 401}
  	else
  		return @current_user
  	end

  end

end

app/controllers/comments_controller.rb
class  CommentsController < ApplicationController


	def create
		if (params[:comment][:parent_type] == 'Post')
			@parent = Post.find(params[:comment][:parent_id])
		else
			@parent = Comment.find(params[:comment][:parent_id])
		end

		@comment = Comment.create(
				content: params[:comment][:content],
				user_id: current_user.id,
				parent: @parent
				# or you can do
				# user: current_user
			)


		Resque.enqueue(CommentMailWorker, @comment.id)


	end

end

app/controllers/likes_controller.rb
class  LikesController < ApplicationController

	def toggle
		# Assignment: use the method in models for user_can_like in both posts and comments
		like = Like.find_by(
			parent_type: params[:parent_type], 	
			parent_id: params[:parent_id],
			user: current_user
			)

		if like.blank?
			like = Like.create(
					parent_type: params[:parent_type], 	
					parent_id: params[:parent_id],
					user: current_user
				)
			@liked = true
		else

			like.destroy
			@liked = false

		end
			
	end

end

app/controllers/posts_controller.rb
class  PostsController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:create]
	before_action :authenticate_user_custom, only: [:create]

	def index

		@post = Post.new
		@comment = Comment.new
		# @posts = Post.all
		@page = params[:page].blank? ? 1 : params[:page].to_i
		@count = params[:count].blank? ? 2 : params[:count].to_i

		@max_pages = Post.all.length/@count
		
		@posts = Post.offset((@page - 1) * @count).limit(@count)


		respond_to do |format|
			format.html 
			format.js
			format.json {render json: @posts, adapter: :json, root: "posts"}
		end
		
	end

	def create
		@post = Post.create(
				content: params[:post][:content],
				user_id: @current_user.id
				# or you can do
				# user: current_user
			)
		@comment = Comment.new

		respond_to do |format|
			format.html
			format.js
			format.json {render json: @post}
		end


	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)

      byebug

      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
      
        sign_in_and_redirect @user
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users_controller.rb
class  UsersController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:api_sign_in]


	def my_profile
		@user = current_user
	end


	def update
		
		current_user.update(
				email: params[:user][:email],
				avatar: params[:user][:avatar]
			)

		redirect_to action: 'my_profile'
	end

	def api_sign_in
		user = User.find_by_email(params[:username])
		
		if (user.valid_password? params[:password])
			user.set_auth_token
			return render json: user
		else
			return render json: {message: "Invalid Username or Password"}, status: 401
		end
	end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li>
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-user">
		<small>
			By <%= comment.user.email %> at <%= comment.created_at.to_date %>
		</small>
	</p>
</li>

app/views/comments/create.js.erb
var newComment = $('<%= escape_javascript render "comment", comment: @comment %>');

if ('<%= @comment.parent_type %>' == 'Post'){
	$('#post<%= @comment.parent_id %> .post-comments-container ul').prepend(newComment);
}else{
// assignment
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialchemy </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <script src="
https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" %>
</head>
<body>

	<header id="body-header">
		<div class="logo animated bounce">
			<p>Socialchemy</p>
		</div>
		<nav>
			<ul>
				<% if user_signed_in? %>
				<li id="current_user_email"><%= current_user.email %></li>
				<li id="current_user_name"><%= current_user.name %></li>
				<li>
					<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
				</li>
				<% else %>
				<li>
					<%= link_to "Sign In", new_user_session_path %>
				</li>
				<li>
					<%= link_to "Sign Up", new_user_registration_path %>
				</li>
				<% end %>
			</ul>
		</nav>
	</header>

<%= yield %>

	<% if user_signed_in? %>
	<div id="user-chat-box">
		<ul id="chat-messages-list">
			<li class="other-message">
				<span>Other Message</span>
			</li>
			<li class="self-message">
				<span>
					Self Message
				</span>
				
			</li>

		</ul>
		<div id="chat-message-input-container">
			<input id="chat-message-input" placeholder="Type message here">
			<button id="send-message"><i class="fa fa-thumbs-up"></i></button>
		</div>

	</div>
	<% end %>


	<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" %>
	<script type="text/javascript">
		new WOW().init()
	</script>
</body>
</html>

app/views/likes/toggle.js.erb
<% if params[:parent_type] == "Post" %>
	var like = '<i class="fa fa-thumbs-o-up"></i>';
	if (<%= @liked %> == true){
		like = '<i class="fa fa-thumbs-o-down"></i>'
	}
	$("#post" + <%= params[:parent_id] %> + ">.post-likes>.like-status>a").html(like);
<% else %>	

<% end %>

app/views/posts/_post.html.erb
<li id="post<%= post.id %>" class="wow fadeInUp">
	<p class="post-content"><%= post.content %></p>
	<p class="post-user">
		<small>
			By <%= post.user.email %> 
			at <%= post.created_at.to_date %>
		</small>
	</p>
	<p class="post-likes">
		<span class="like-status">
		
				<%= link_to post.current_like_status_string(current_user).html_safe, like_toggle_path(parent_type: "Post", parent_id: post.id), method: :get, remote: true %>

		</span>
		
		<span class="like-count"><%= post.likes.length %></span>
	</p>

	<div class="post-comments-container">
		<h4>Comments</h4>
		<%= form_for @comment, remote: true do |fc| %>
			<input type="hidden" name="comment[parent_type]" value="Post">
			<input type="hidden" name="comment[parent_id]" value="<%= post.id %>">
			
			<%= fc.label :content, "New Comment" %>
			<%= fc.text_field :content %>

			<%= fc.submit %>
		<%end%>
		<ul>
			<% post.comments.reverse.each do |comment| %>
				<%= render 'comments/comment', comment: comment %>
			<% end %>
		</ul>

	</div>
</li>

app/views/posts/create.js.erb
var newPost = $('<%= escape_javascript render "post", post: @post %>');


$('.posts-list-container ul').prepend(newPost);

app/views/posts/index.html.erb
<main class="body-main">
	<h3>Posts</h3>
	<p class="page_numbers">
		G<% (1..@max_pages).each do |mp| %>
			<a href="/?page=<%=mp%>&count=<%= @count %>"><%= mp %></a>
		<% end %>gle
	</p>

	<%= form_for @post, remote: true do |f| %>
		<%= f.label :content, "New Post" %>
		<%= f.text_field :content %>

		<%= f.submit %>
	<% end %>

	<div class="left-sidebar"></div>
	<div class="posts-list-container center-container">
		<ul id="posts-list">
		<% @posts.each do |p| %>
			<%= render "post", post: p %>
		<% end %>
		</ul>
		
	</div>
	<div class="right-sidebar"></div>

</main>
<script type="text/javascript">
	var nextPage = 2;
	var postsAjax;
	var maxPageReached = false;
</script>
<script type="text/javascript">
	
	function getPosts(){
		 postsAjax = $.ajax({
			type: 'GET',
			url: '/',
			data: {
				page: nextPage,
				count: 2
			},
			dataType: 'script'
		})
		
	}

	var initialScroll = 0;

	$(window).scroll(function(){
		if (window.scrollY > initialScroll + 200 && postsAjax == undefined ){
			console.log('fired')
			getPosts();
			initialScroll = window.scrollY;
		}
	});

</script>

app/views/posts/index.js.erb
<% @posts.each do |ps| %>
	
	$('#posts-list').append("<%= escape_javascript render 'post', post: ps %>")

<% end %>


nextPage = <%=  @page + 1 %>;
postsAjax = undefined;
// if @page == @max_pages

	// max

app/views/users/my_profile.html.erb
<main>
	<h1>User Profile</h1>

	<div>
		<%= image_tag current_user.avatar %>
	</div>

	<%= form_for @user do |f| %>

		<div class="form-field">

			<%= f.label :email %>
			<%= f.email_field :email %>
		</div>

		<div class="form-field">

			<%= f.label :avatar %>
			<%= f.file_field :avatar %>

		</div>

		<div class="form-field">
			<%= f.submit "Update Profile" %>
		</div>


	<% end %>


</main>